### ISSUE TITLE
Why to calculate K.means during calculate loss?

### ISSUE THREAD

**Issue by JINwonLEE** [peikexin9/deepxplore#10]
Hi I'm graduate students who are interesting in DeepXplore. Actually I saw your presentation in conference. After the conference I tried to understand your source code more deeply, however I got some issues. 

One thing is that when you calculate the loss, actually not only loss(loss*, loss*_neuron,...) you all add K.means function to them. I have no idea why do we calculate the means of such losses. For instance, in case of loss1, is the tensor type just one scalar value which represents confidence price of label orig_label? If not, can you give me an advice?

Thanks

**Comment by peikexin9** [comment]
Hi Jinwon, you are right. K.means on most losses have no specific meaning. I used there just in case it's not a scalar value. I think you can safely discard them if the input is already a scalar value.
