### ISSUE TITLE
cannot run gen_diff.py under Drebin

### ISSUE THREAD

**Issue by agentnirt** [peikexin9/deepxplore#12]
got the error below when run "python gen_diff.py 1 0.5 20 50 0" under Drebin, do you know where the issue might be?

ValueError: Dimension 0 in both shapes must be equal, but are 295 and 545334 for 'Assign' (op: 'Assign') with input shapes: [295,200], [545334,200].

**Comment by peikexin9** [comment]
Hi @agentnirt, seems I can run the same command with no errors? is that the same code?

**Comment by wazxser** [comment]
Maybe it is because that the Drebin needs the origin dataset that can be download from the official website.

**Comment by 123wjl123** [comment]
> got the error below when run "python gen_diff.py 1 0.5 20 50 0" under Drebin, do you know where the issue might be?
> 
> ValueError: Dimension 0 in both shapes must be equal, but are 295 and 545334 for 'Assign' (op: 'Assign') with input shapes: [295,200], [545334,200].

hi，I have meet the same problem. Have you solved it?

**Comment by 123wjl123** [comment]
> Hi @agentnirt, seems I can run the same command with no errors? is that the same code?

Hi, I meet the same trouble with @agentnirt , and I don't know how to solve this TOT,  can you teach me?

**Comment by 123wjl123** [comment]
> Maybe it is because that the Drebin needs the origin dataset that can be download from the official website.

hi，have you solve the problem？I meet the same problem with @agentnirt . Can you teach me please?
