### ISSUE TITLE
Ambiguity about Coverage

### ISSUE THREAD

**Issue by alipourm** [peikexin9/deepxplore#15]
It's not clear how covered is calculated. 
- Why are the neurons scaled?
- Why are they averaged to decide to decide if they are fired? 

https://github.com/peikexin9/deepxplore/blob/dc8b405cb58bdc8e26d7ed0beeaf784115bc3ee7/PDF/utils.py#L93

**Comment by peikexin9** [comment]
Sometimes one layer's output is in different order of magnitude with another. So to enable setting a global threshold to determine if a neuron is fired, I make each layer in same scale.
For a convolution layer, I treat the neuron's output as the average of values in feature map, so it's averaged.
