### ISSUE TITLE
Caffe instance

### ISSUE THREAD

**Issue by rajasekharponakala** [peikexin9/deepxplore#16]
Hi Pei!,

what is the feasibility of deploying the framework described in your paper to the Caffe based instance, is it possible enough.  

Thanks-
Rajasehkar

**Comment by peikexin9** [comment]
Hi Rajasehkar, yeah it's possible. I believe Caffe also supports computing the gradient of any intermediate neuron w.r.t. input tensor. That's the core functionality we need using any framework.

**Comment by rajasekharponakala** [comment]
Thanks Pei.
