### ISSUE TITLE
GoogleNet for Image Classification

### ISSUE THREAD

**Issue by rajasekharponakala** [peikexin9/deepxplore#18]
Hi Pei,

There is an image classification task for identifying an image consisting of a Bus, Car, Van, Truck. This is implemented by using GoogleNet (Caffe) model. Now, in order to fool the model by identifying a Bus as Car, how can we use DeepXplore for this particular type of classification.

Thanks.

**Comment by peikexin9** [comment]
Hi @rajasekharponakala, sorry for the late reply. If there are Keras model for GoogleNet, I believe you can import the GoogleNet model in gen_diff.py like what is done for other models: "from keras.applications.vgg19 import VGG19". Then use it the same way as other models, e.g., replace VGG19 with the GoogleNet. There should be nothing else significant to change.

**Comment by rajasekharponakala** [comment]
No problem!. Thanks for the reply. I'll try doing that.
