### ISSUE TITLE
occlusion dark spots

### ISSUE THREAD

**Issue by rajasekharponakala** [peikexin9/deepxplore#19]
Hi,

could you help me to get the blackout dark spots on the generated images, in the way you used in the paper (Figure 8). 
![screenshot from 2018-11-11 02-08-26](https://user-images.githubusercontent.com/11900597/48305072-bfa4d900-e556-11e8-85ea-b02237fd07eb.png)

Here is what my images look alike: 
![bus-moccl-orig-18](https://user-images.githubusercontent.com/11900597/48305026-3ab9bf80-e556-11e8-8653-a39bda0ca81f.png)
![bus-moccl-perturb-17](https://user-images.githubusercontent.com/11900597/48305029-3ab9bf80-e556-11e8-80bd-25fa666c8907.png)

can i get the shorter dark rectangles, could you reproduce the size that we have to use for `occl_size` with the `arg.parse()`.
Thanks.

**Comment by peikexin9** [comment]
Sorry @rajasekharponakala, I do not quite remember the exact size. From just the look, I suspect it should be something around 5x5?

**Comment by rajasekharponakala** [comment]
@peikexin9: Thanks. For example, is the syntax correct?
 `python gen_diff.py -occl_size 5x5 blackout 1 0.1 10 100 50 0`

**Comment by peikexin9** [comment]
@rajasekharponakala try something like -occl_size (5,5)?

**Comment by rajasekharponakala** [comment]
@peikexin9: As the paper discuss on domain-specific constraints, can we consider them as high-dimensional spaces, which are linear in nature and causing adversarial examples?

**Comment by peikexin9** [comment]
@rajasekharponakala I would think so. There must be a space linear to these transformations that the NN should be invariant of (while it is actually not thus resulting in the adversarial example).
