### ISSUE TITLE
there are two problem I need your help when I run the program Driving.

### ISSUE THREAD

**Issue by BT123** [peikexin9/deepxplore#5]
The command I used is:
       python gen_diff.py occl -t 0 1.0 0.1 10 10 10 0
And my env is Tensorflow1.4.0，keras 2.1.1，and so on.

the problem is :
/deep-test/deepxplore/Driving/utils.py:133: RuntimeWarning: invalid value encountered in divide
  intermediate_layer_output.max() - intermediate_layer_output.min())

Traceback (most recent call last):
  File "gen_diff.py", line 155, in <module>
    gen_img_deprocessed = draw_arrow(deprocess_image(gen_img), angle1, angle2, angle3)
  File "/deep-test/deepxplore/Driving/utils.py", line 49, in deprocess_image
    x[:, :, 1] += 116.779
IndexError: index 1 is out of bounds for axis 2 with size 1

I changed the version of Keras, but it's useless.

So, I want to get your help to deal with it.

Looking forward to your reply!

**Comment by BT123** [comment]
The last one I mentioned before has been solved.

It's my mistake to modify the deprocess_image() function.

And I git clone again and there no more have the problem, but the first one still exist though it doesn't influence the process.

Looking forward to your reply!

![image](https://user-images.githubusercontent.com/9165608/33419523-cb82d3e8-d5e5-11e7-9444-b781a528979e.png)

**Comment by peikexin9** [comment]
Hi @BT123 , seems I cannot reproduce the warning. It is possible that intermediate_layer_output's max and min are too close such that divided by zero may happen. One workaround may be that you can catch this warning and simply replace all output values involved in this division to be just 1.
