### ISSUE TITLE
Why do you add 103.939 to R channel of image in deprocess_image function?

### ISSUE THREAD

**Issue by BT123** [peikexin9/deepxplore#7]

**Comment by BT123** [comment]
Sorry, I have known the answer of the above problem.
But I still have another one. 
Although I choose the occl constraint method, all image data of the saved image after each iteration will become a little light.
Can you give me some advice about this problem?

**Comment by peikexin9** [comment]
Hi @BT123, seems I can generate the occlusion using "python gen_diff.py occl 1 0.1 10 10 50 0".

**Comment by BT123** [comment]
ok, I will try with your parameter.
Thank you ~
