### ISSUE TITLE
Why to calculate mean in constraint_black function？

### ISSUE THREAD

**Issue by BT123** [peikexin9/deepxplore#9]
In this function, only when the mean of the 10*10 gradient value bigger than zero, we will add them to the original image data.
I still haven't understood the reason for it.
Can you give me some advice?
Thank you~~

**Comment by peikexin9** [comment]
Hi @BT123 I think it fixes a square area and decreases each pixel value of that square by same amount, if the averaged gradient of that squared area is negative. My assumption is that the negative averaged gradient of that area means if decreasing each pixel in that area by the same amount, the overall objective function is optimized roughly in the similar direction as performing gradient descent directly.

**Comment by yuangao2** [comment]
Could you please explain a little bit more about why we need to check "if np.mean(patch) < 0" before changing the value inside the patch to all 1s? I still don't understand. It seems if I remove that statement, I can still generate images with different predictions

**Comment by peikexin9** [comment]
Hi @yuangao2, you are right, this is just to (hopefully) make the changes roughly follow the gradient direction (towards optimizing objective). But as gradient-based method has no guarantees and also many constraints are exerted here, it is possible that, like you did, it is still going to the direction of optimizing the objective without requiring the average gradient to be smaller 0.

**Comment by yuangao2** [comment]
Thanks!
